config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :posts
  resources :contacts, only: [:new, :create]

  get 'about' => 'welcome#about'
  get 'portfolio' => 'welcome#portfolio'
  get 'prints' => 'welcome#prints'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,  :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)([\w]{2,})\z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha => true

  def headers
    {
      :subject => "Contact Form",
      :to => "brittonbaumann@GreatBrittonPhotography.com",
      :from => %("#{name}" <#{email}>)
    }

  end

end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true, length: { minimum: 5}
  validates :body, presence: true

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Message failed to send.'
      render :new
    end
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts_home = Post.all.order('created_at DESC').limit(3)
  end

  def portfolio
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/create.html.erb
<div class="jumbotron heading text-center">
  <h1>Thank You For Your Message!</h1>
  <p>
    I will respond as soon as I can.
  </p>
</div>

app/views/contacts/new.html.erb
<section class="container-fluid contact-section">
  <%= image_tag ( "NYC_man_city_crop.jpg"), :alt => "NYC.", :class => "contact-img" %>

  <div class="contact-social">
    <h4 class="text-left touch">WAYS TO GET IN TOUCH</h4>
    <div class="col-xs-12 col-sm-6 text-left social-col-1 social-container">
      <a href="https://www.facebook.com/britt.baumann.7" class="social-con" target="_blank"><i class="fa fa-facebook fa-lg social-label" aria-hidden="true"></i><p class="social-label face-social"> Britt Baumann</p><br/></a>
      <a href="https://www.instagram.com/greatbritton85/" class="social-con" target="_blank"><i class="fa fa-instagram fa-lg social-label" aria-hidden="true"></i><p class="social-label insta-social">@greatbritton85</p><br/></a>
    </div>
    <div class="col-xs-12 col-sm-6 text-left social-col-2 social-container social-bottom">
      <a href="https://twitter.com/GreatBritton85" class="social-con" target="_blank"><i class="fa fa-twitter fa-lg social-label" aria-hidden="true"></i><p class="social-label">@greatbritton85</p><br/></a>
      <a href="mailto:BrittonBaumann@greatbrittonphotography.com" class="social-con" target="_top"><i class="fa fa-envelope fa-lg social-label" aria-hidden="true"></i><p class="social-label">BrittonBaumann@greatbrittonphotography.com</p><br/></a>
    </div>
    <h4 class="text-left touch">CONTACT FORM</h4>
    <div class="col-xs-12 text-center">
      <%= form_for @contact do |f| %>
        <%= f.label :name, 'Name :', :class => 'labels' %><br />
        <%= f.text_field :name, :class => 'label-box', required: true %>

        <br />

        <%= f.label :email, 'Email :', :class => 'labels' %><br />
        <%= f.email_field :email, :class => 'label-box', required: true %>

        <br />

        <%= f.label :message, 'Message :', :class => 'labels' %><br />
        <%= f.text_area :message, :class => 'label-box', as: :text %>

        <br />

        <div class="hidden">
          <%= f.label :nickname %><br />
          <%= f.text_field :nickname, hint: 'leave this field blank' %>
        </div>

        <%= f.submit 'Send Message', class: "button" %><br />

      <% end %>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photography</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Cinzel|Cinzel+Decorative|Italianno|Spectral+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet">
  </head>

  <body oncontextmenu="return false;">
    <div class="main-container">
      <!-- Navbar -->
      <nav class="navbar navbar-default navbar-fixed-top slow" id="nav">
        <div class="container-fluid nav-set">
          <input type="checkbox" id="navbar-toggle-cbox">
          <div class="navbar-header">
            <button for="navbar-toggle-cbox" id="nav-ham" class="navbar-toggle collapsed"  data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar top-bar"></span>
              <span class="icon-bar bottom-bar"></span>
            </button>

              <a class="logo-link" href="/"><%= image_tag("GB-Front-Crown-5.png", :alt => "Modern bathroom", :class => "logo-2", :data => {:number => 0}) %>
              <%= image_tag("GB-full-crop-5.png", :alt => "Modern bathroom", :class => "logo", :data => {:number => 0}) %></a>
          </div>
          <div id="navbar" class="navbar-right navbar-collapse collapse ">
            <ul class="nav navbar-nav">
              <li><a href="/portfolio">Portfolio</a></li>
              <li><a href="/about">About</a></li>
              <li><a href="/contacts/new">Contact</a></li>
              <li><a href="/posts">Blog</a></li>
            </ul>
          </div>
        </div>
      </nav> <!-- /Nabvar -->

      <div id="copy-alert">
        <p>These images are protected by copyright. All
          rights reserved. Unauthorized use is prohibited.</p>
      </div>
      <%= yield %>

      <!-- Footer -->
      <footer class="footer">
        <div class="container text-center foot-container">
          <a href="https://www.instagram.com/greatbritton85/" class="social-foot" target="_blank"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a>
          <a href="https://twitter.com/GreatBritton85" class="social-foot" target="_blank"><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></a>
          <a href="https://www.facebook.com/britt.baumann.7" class="social-foot" target="_blank"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a>
          <p class="foot-copyright"><small> &copy; 2018 Britton Baumann | All Rights Reserved </small></p>
        </div>
      </footer>
    </div>

  </body>
</html>

app/views/posts/_blog.html.erb
<!-- Blog section -->


<!-- <section id="blog" class=" content-section text-center">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 blog-index-container">
        <h2 class="col-xs-6 col-xs-offset-3 index-blog-header">Recent Blog Posts</h2>
        <% @posts_home.each do |post| %>
          <div class=" col-sm-4 posts" >
            <h3><%= link_to post.title, post %></h3>
              <%= link_to image_tag(post.image, :class => "col-xs-12"), post %>
            <p>
              <%= post.body.truncate(100,separator: /\s/) %>
            </p>
          </div>
        <% end %>
      </div>

    </div>
  </div>
</section> -->

app/views/posts/index.html.erb
<section class="container-fluid">
  <header>
    <h1 class="blog-head">Blog</h1>
  </header>
  <nav class="blog-nav">
    <a href="#" class="blog-links recent">Recent</a>
    <a href="#" class="blog-links">Popular</a>
    <a href="#" class="blog-links">What</a>
    <a href="#" class="blog-links">Cityscape</a>
  </nav>
  <main>

    <h1 class="blog-h1 text-center">First post coming soon!</h1>
    <!-- <div class="recent-blog">
      <h1 class="text-center">Hi</h1>
      <a class="new-post"href="#">New Post</a>
    </div>
    <% @posts.each do |post| %>
      <div class="blog-posts">
        <h3><%= link_to post.title, post, :class => "blog-title" %></h3>
        <%= link_to image_tag(post.image,  :class => "blog-image"), post %>
      </div>
    <% end %> -->

  </main>
</section>

app/views/posts/show.html.erb
<section class="container-fluid show-container">
  <header>
    <h1 class="blog-show-head"><%= @post.title %></h1>
  </header>
  <main>
    <%= image_tag(@post.image, :class => "blog-show-img") %>
    <p class="blog-show-body"><%= @post.body %></p>
  </main>
</section>

app/views/welcome/about.html.erb
<section class="container-fluid about-section">
  <h1 class="about-head">Britton Baumann</h1>
  <%= image_tag ( "Britt_head.jpg"), :class => "about-img" %>
  <main class="about-main">
    <h4 class="about-sm-head">About</h4>
    <p class="about-p">
      I'm a photographer and web developer based in St. Cloud, MN. I love to photograph cityscapes and landscapes but I do a lot of work in real estate. The languages I work with in web development are javascript and ruby.
      <br/>
      <br/>
   	 I grew up in North Branch, Minnesota: a small rural town north of the Twin Cities. In my younger years I was obsessed with sports and still am today. I played football, basketball and tennis in high school and after high school I had the opportunity to continue my football career while attending the University of Minnesota Duluth.  During my time at UMD I majored in sociology and minored in history.
	    <br/>
      <br/>
	After college I kept pursuing football and had the opportunity to tryout and workout with multiple professionals teams in different leagues. Years of training and tryouts went by but unfortunately I wasn’t able to break through. This is what lead me to photography and web development.
      <br/>
      <br/>
	When all the training and football was over, I was left without one of my passions: playing sports. Having more free time I looked for a hobby. I have always been interested in photography; not only that but I also like to learn new skills. I ended up buying a Nikon D3300 and tried to learn as much as I could about photography and editing through articles, blogs, and videos. With some new knowledge I took a vacation to Glacier National Park and during this time tested out my new skills and camera. I fell in love with photography there and haven’t looked back.
      <br/>
      <br/>
	After the trip I would continue to work on my photography and keep learning. Having the curiosity and willingness to learn as many things as I can I found web development. I would eventually pursue this interest along with photography and took a bootcamp to learn more. I’m glad I pursued web development because it helped me think outside the box and complemented my photography.
      <br/>
      <br/>
	Which leads me to where I am today. I continue to add to these skills and expand my knowledge in everything photography and web development. I’m in the process of learning more about graphic/web design and also videography to complement my skill set. I would have never thought I would be doing what I am doing when I was younger but I am glad I have found my passions in life.
      <br/>
      <br/>
	It’s been one heck of a ride so far and can’t wait to see where it takes me.


    </p>
  </main>
</section>

app/views/welcome/index.html.erb
<div class="back-img"></div>
<div class="container-fluid">

  <section class="buisness">
    <div class="buis flex-container">
      <div>
        <a class="buisness-link" href="mailto:brittonbaumann@greatbrittonphotography.com">Buisness Inquiries</a>
      </div>
      <div>
        <h6 class="buisness-h">
          Photographer  &#38; Web Developer
        </h6>
        <div class="social-links">
          <a href="https://www.instagram.com/greatbritton85/" class="social" target="_blank"><i class="fa fa-instagram fa-2x" aria-hidden="true"></i></a>
          <a href="https://twitter.com/GreatBritton85" class="social" target="_blank"><i class="fa fa-twitter fa-2x" aria-hidden="true"></i></a>
          <a href="https://www.facebook.com/britt.baumann.7" class="social" target="_blank"><i class="fa fa-facebook fa-2x" aria-hidden="true"></i></a>
        </div>
      </div>
    </div>
  </section>
  <section class="main-points">
    <div class="points points-port">
      <%= link_to portfolio_path , :class => 'points-port-link' do %>
        <h5 class="link-head pull-right">Portfolio</h5>
      <% end %>
    </div>
    <div class="points points-blog">
      <%= link_to posts_path , :class => 'points-blog-link' do %>
        <h5 class="link-head pull-right">Blog</h5>
      <% end %>
    </div>
    <div class="points points-print">
      <%= link_to prints_path , :class => 'points-print-link' do %>
        <h5 class="link-head pull-right">Prints</h5>
      <% end %>
    </div>
  </section>
</div>

app/views/welcome/portfolio.html.erb
<div class="container-fluid portfolio-cont">
  <header>
    <h1 class="port-header">Portfolio</h1>
  </header>
  <nav class="port-nav">
    <a href="#" id="cityscape-link" class="port-links active-color">Cityscape</a>
      <a href="#" id="landscape-link" class="port-links">Landscape</a>
    <a href="#" id="real-estate-link" class="port-links">Real Estate</a>
    <!-- <a href="#" id="headshot-link" class="port-links">Headshots</a> -->
  </nav>
  <main>
    <div id="modal-container">
        <%= image_tag("", :alt => "Britt", :id => "modal-content" ) %>
        <a id="close-modal">
          <span id="top-bar" class="icon-bar top-bar"></span>
          <span id="bottom-bar" class="icon-bar bottom-bar"></span>
        </a>
        <a class="modal-nav port-prev" id="port-prev"><i class="fa fa-chevron-left fa-2x prev-logo" aria-hidden="true"></i></a>
        <a class="modal-nav port-next" id="port-next" ><i class="fa fa-chevron-right fa-2x next-logo" aria-hidden="true"></i></a>
    </div>
    <section>
      <div class="port-row">
        <section class="cityscape-port port-page active">
          <div class="port-column">
            <%= image_tag("Duluth_bw_city.jpg", :alt => "Duluth, MN. Black and white photo of Duluth arial lift bridge", :class => "img-city", :data => {:number => 0}) %>
            <%= image_tag("MSP_stonetop_city.jpg", :alt => "Sunset photo of Minneapolis from stone arch bridge.", :class => "img-city", :data => {:number => 1}) %>
            <%= image_tag("NYC_freeway_city.jpg", :alt => "Photo of Downtown Manhatten", :class => "img-city", :data => {:number => 2}) %>
            <%= image_tag("Duluth_day_city.jpg", :alt => "Duluth, MN. Day photo of Duluth arial lift bridge", :class => "img-city", :data => {:number => 3}) %>
            <%= image_tag("NYC_man_city.jpg", :alt => "Photo of Manhatten", :class => "img-city", :data => {:number => 4}) %>
            <%= image_tag("NYC_mem_city.jpg", :alt => "Photo of 9/11 memorial", :class => "img-city", :data => {:number => 5}) %>
          </div>
          <div class="port-column">
            <%= image_tag("MSP_car_city.jpg", :alt => "Image of Minneapolis at night with car trails.", :class => "img-city",:data => {:number => 6}) %>
            <%= image_tag("Duluth_night_city.jpg", :alt => "Duluth, MN. Night photo of Duluth arial lift bridge", :class => "img-city", :data => {:number => 7}) %>
            <%= image_tag("MSP_stonewater_city.jpg", :alt => "Photo of Minneapolis from below stone arch bridge", :class => "img-city", :data => {:number => 8}) %>
            <%= image_tag("NYC_sun_city.jpg", :alt => "Photo of New Jersey from manhatten", :class => "img-city",:data => {:number => 9}) %>
            <%= image_tag("NYC_freedom_city.jpg", :alt => "Photo of Freedom tower in NYC.", :class => "img-city", :data => {:number => 10}) %>
            <%= image_tag("Seattle_city.jpg", :alt => "Photo of Seattle ", :class => "img-city", :data => {:number => 11}) %>
          </div>
        </section>
        <section class="landscape-port port-page">
          <div class="port-column">
            <%= image_tag("Split_rock_land.jpg", :alt => "Photo of Split Rock Lighthouse in MN", :class => "img-land",:data => {:number => 0}) %>
            <%= image_tag("Skagway_land.jpg", :alt => "Photo of Skagway, AK", :class => "img-land", :data => {:number => 1}) %>
            <%= image_tag("Yellow_waterfall_land.jpg", :alt => "Photo of waterfall in Yellowstone National Park ", :class => "img-land", :data => {:number => 2}) %>
            <%= image_tag("Alaska_glac_land.jpg", :alt => "Photo of glacier falling", :class => "img-land", :data => {:number => 3}) %>
            <%= image_tag("MT_reading2_land.jpg", :alt => "Photo of Man reading in Glacier National Park in MT", :class => "img-land", :data => {:number => 4}) %>
            <%= image_tag("Rush_flags_land.jpg", :alt => "Photo of Mount Rushmore.", :class => "img-land", :data => {:number => 5}) %>
          </div>
          <div class="port-column">
            <%= image_tag("MT_road_land.jpg", :alt => "Photo of Smoke filled sunrise in MT", :class => "img-land", :data => {:number => 6}) %>
            <%= image_tag("Cloud_tree_land.jpg", :alt => "Photo of frost covered tree.", :class => "img-land", :data => {:number => 7}) %>
            <%= image_tag("Alaska_fog_land.jpg", :alt => "Photo of a foggy mountain in AK.", :class => "img-land", :data => {:number => 8}) %>
            <%= image_tag("MT_tess_land.jpg", :alt => "Photo of a ranch in MT with smoke filled skies.", :class => "img-land", :data => {:number => 9}) %>
            <%= image_tag("MT_chair_land.jpg", :alt => "Photo of cabin in MT with smoke filled skies.", :class => "img-land", :data => {:number => 10}) %>
          </div>
        </section>
        <section class="real-estate-port port-page">
          <div class="port-column">
            <%= image_tag("bath.jpg", :alt => "Modern bathroom", :class => "img-real", :data => {:number => 0}) %>
            <%= image_tag("cabin.jpg", :alt => "Cabin livingroom", :class => "img-real", :data => {:number => 1}) %>
            <%= image_tag("bed-cup.jpg", :alt => "Master bedroom", :class => "img-real",:data => {:number => 2}) %>
            <%= image_tag("living.jpg", :alt => "Livingroom", :class => "img-real", :data => {:number => 3}) %>
            <%= image_tag("Kitchen-in.jpg", :alt => "Kitchen looking towards the house", :class => "img-real", :data => {:number => 4}) %>
            <%= image_tag("Kitchen-out.jpg", :alt => "Kitchen looking outside.", :class => "img-real", :data => {:number => 5}) %>
          </div>
          <div class="port-column">
            <%= image_tag("bar.jpg", :alt => "Bar", :class => "img-real", :data => {:number => 6}) %>
            <%= image_tag("m-kitchen.jpg", :alt => "Modern kitchen", :class => "img-real", :data => {:number => 7}) %>
            <%= image_tag("small-bath.jpg", :alt => "Guest bathroom.", :class => "img-real", :data => {:number => 8}) %>
            <%= image_tag("bed.jpg", :alt => "Modern bedroom", :class => "img-real", :data => {:number => 9}) %>
            <%= image_tag("guest-bedroom.jpg", :alt => "Guest bedroom", :class => "img-real", :data => {:number => 10}) %>
          </div>
        </section>
      </div>
    </section>
  </main>
</div>

app/views/welcome/prints.html.erb
<div class="container">
  <h1 class="text-center prints">Coming Soon!</h1>
</div>